#%RAML 1.0
title: Procesar AFIP
version: 1.0

/procesar:

  post:
    displayName: Post Procesar AFIP
    body:
      application/json:
        properties:
          file_stringbase64:
            type: string
            required: true
            displayName: file_stringbase64
            description: "Contenido de archivo en formato StringBase64"
          file_type:
            type: string
            required: true
            displayName: file_type
            description: "Tipo de archivo del campo file_stringbase64"
            example: "image/png"
#        example:
#          value: 
#            file_stringbase64: "codigobase64"
#            file_type: "image/png"
    responses:
      200:
        body:
          application/json:
            type: object
            example: !include examples/AFIPExample.raml